title: Mehmet Canayaz
description:  Mehmet's Github Repo
url: https://mehmetcanayaz.github.io/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
